apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-matan
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-mata
  template:
    metadata:
      labels:
        app: nginx-matan
    spec:
      hostname: nginx-matan
      containers:
        - name: nginx-matan
          image: gcr.io/apiiro/test/nginx-test/nginx-test:latest
          imagePullPolicy: Always
